### PR TITLE
Proposed scheme for dataset - objective - solver dependancy

### PR DESCRIPTION
**Pull request by tanglef**
Poke @mathurinm, to improve of course
I really wanted to stay with the same images and display as the `benchopt_schema` so it's easier to match things up when reading for new users

### CODE REVIEW

**Comment by tomMoral** [comment]
can you share the rendered image?

**Comment by tanglef** [comment]
Capture d’écran de 2022-11-18 10-42-51

**Comment by tomMoral** [comment]
Can you add `get_result` and `compute`?

**Comment by tomMoral** [comment]
Forgot to say it but it looks very nice!!!

**Comment by tanglef** [comment]
> Can you add `get_result` and `compute`?

Done now 🙂 
Capture d’écran de 2022-11-18 11-33-24

**Comment by tomMoral** [comment]
Nice!! :) Otherwise, this seems a good start.

Dependency relation `between`?

**Comment by mathurinm** [comment]
Thanks a lot @tanglef as Thomas said it's exactly what we needed. two remarks

- dependency with a e 
- From a pythonic point of view we're talking about the function itself so it's indeed `get_result` but it may be clearer that it's a function by using the function call `get_result()`. WDYT?

**Comment by mathurinm** [comment]
"for solvers to compute the objective" may be confusing, because it's the objective which computes the objectives. 

'For solvers to solve the optimization problem?'

**Comment by mathurinm** [comment]
LGTM!

**Review by tomMoral — APPROVED** [review]
LGTM! thanks @tanglef

**Pull request merged**
